version: "3.8"

services:
  database:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: metricalo_lab
      MYSQL_DATABASE: metricalo
      MYSQL_USER: kelvin
      MYSQL_PASSWORD: kelvin_metricalo
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - metricalo

  php:
    build: docker/php-fpm
    environment:
      - DATABASE_URL=mysql://root:metricalo_lab@database:3306/metricalo
    volumes:
      - ./:/var/www/html
    networks:
      - metricalo

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    environment:
      - DATABASE_URL=mysql://root:metricalo_lab@database:3306/metricalo
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - metricalo

networks:
  metricalo:

